#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Thu Oct 17 14:54:06 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from plot_panel import PlotPanel
from plot_panel import PlotPanel
# end wxGlade


class ThePanel(PlotPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ThePanel.__init__
        kwds["style"] = kwds.get("style", 0)
        PlotPanel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ThePanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ThePanel.__do_layout
        self.Layout()
        # end wxGlade

# end of class ThePanel

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 320))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "open", "")
        self.Bind(wx.EVT_MENU, self.on_open, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "saveas", "")
        self.Bind(wx.EVT_MENU, self.on_saveas, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "quit", "")
        self.Bind(wx.EVT_MENU, self.on_close, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "file")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.plot_panel = ThePanel(self, wx.ID_ANY)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.btn_refresh = wx.Button(self.panel_1, wx.ID_ANY, "Refresh")
        self.btn_gen_data = wx.Button(self.panel_1, wx.ID_ANY, "Acquire data")
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_savepath = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        self.btn_browse = wx.Button(self.panel_2, wx.ID_ANY, "Browse")
        self.btn_save = wx.Button(self.panel_2, wx.ID_ANY, "Save")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_refresh, self.btn_refresh)
        self.Bind(wx.EVT_BUTTON, self.on_gen_data, self.btn_gen_data)
        self.Bind(wx.EVT_TEXT, self.on_path_text_change, self.text_ctrl_savepath)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_path_text_change, self.text_ctrl_savepath)
        self.Bind(wx.EVT_BUTTON, self.on_browse, self.btn_browse)
        self.Bind(wx.EVT_BUTTON, self.on_save, self.btn_save)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.plot_panel, 5, wx.EXPAND, 0)
        sizer_3.Add(self.btn_refresh, 1, wx.EXPAND, 0)
        sizer_3.Add(self.btn_gen_data, 1, 0, 0)
        self.panel_1.SetSizer(sizer_3)
        sizer_1.Add(self.panel_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_savepath, 2, wx.EXPAND, 0)
        sizer_2.Add(self.btn_browse, 1, 0, 0)
        sizer_2.Add(self.btn_save, 1, 0, 0)
        self.panel_2.SetSizer(sizer_2)
        sizer_1.Add(self.panel_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_open(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_open' not implemented!")
        event.Skip()

    def on_saveas(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_saveas' not implemented!")
        event.Skip()

    def on_close(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_close' not implemented!")
        event.Skip()

    def on_refresh(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_refresh' not implemented!")
        event.Skip()

    def on_gen_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_gen_data' not implemented!")
        event.Skip()

    def on_path_text_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_path_text_change' not implemented!")
        event.Skip()

    def on_browse(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_browse' not implemented!")
        event.Skip()

    def on_save(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_save' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
